name: CI/CD for Server

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SERVER }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build Project
        working-directory: ./server
        run: npm run build

  CD:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - name: Validate environment variables
        run: |
          if [ -z "${{ env.VERCEL_ORG_ID }}" ]; then
            echo "VERCEL_ORG_ID is not set"
            exit 1
          fi
          if [ -z "${{ env.VERCEL_PROJECT_ID }}" ]; then
            echo "VERCEL_PROJECT_ID is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "VERCEL_TOKEN is not set"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build project
        working-directory: ./server
        run: npm run build

      - name: Deploy to Vercel
        working-directory: ./server
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ github.event_name }}" = "push" ]; then
            npx vercel --prod --token $VERCEL_TOKEN
          else
            npx vercel --token $VERCEL_TOKEN
          fi
